### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xerta555** [Zackptg5/Curl-For-Android#1]
Hello,
Your compilation sounds very interesting.

However, I have some questions about this:
- are your binaries linked statically or dynamically?
- I don't see binaries for mips32 and mips64 architectures, is that normal?
- Did you compile these binaries with gcc or clang?
- which version of the NDK did you use?

**Comment by Zackptg5** [comment]
Static compile
I don't bother with mips (you're free to add that to the script if you want)
I used latest ndk (r19c) which uses clang. The problem is that zlib (and possibly openssl, didn't t pay attention there) required gcc so the script makes a gcc symlink to clang
