### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by coolkit-carl** [Zackptg5/Curl-For-Android#2]
I run "curl getip.name" on the terminal to prompt "Segmentation fault"

**Comment by Zackptg5** [comment]
Google how to use curl, it's a binary for downloading files from the web. You're current command isn't downloading any valid files so it won't work but it shouldn't seg fault. What's your device and rom and can you send me full logcat after attempting a valid use for curl?

**Comment by Zackptg5** [comment]
Added link to support thread on xda
